package com.opticlanes.parking.model;

/**
 * this class will pass information from the JSON request string to the InformationDao
 * class.  For this reason, it does not include the UUID primaryId which will be generated by 
 * dao.
 * 
 * Fields generated by the dao:
 * 	inquiryID 	UUID
 * 	inquiryTime TIMEUUID;
 * 
 * @author warrenweis
 *
 */
public class Inquiry 
{
	private String macId;
	private String gpsLatitude;
	private String gpsLongtitude;
	private String compassOrient;
	private String osType;
	private String osVer;
	
	public String getMacId() 
	{
		return macId;
	}
	
	public void setMacId(String macId) 
	{
		this.macId = macId;
	}
	
	public String getGpsLatitude() 
	{
		return gpsLatitude;
	}
	
	public void setGpsLatitude(String gpsLatitude) 
	{
		this.gpsLatitude = gpsLatitude;
	}
	
	public String getGpsLongtitude() 
	{
		return gpsLongtitude;
	}
	
	public void setGpsLongtitude(String gpsLongtitude) 
	{
		this.gpsLongtitude = gpsLongtitude;
	}
	
	public String getCompassOrient() 
	{
		return compassOrient;
	}
	
	public void setCompassOrient(String compassOrient) 
	{
		this.compassOrient = compassOrient;
	}
	
	public String getOsType() 
	{
		return osType;
	}
	
	public void setOsType(String osType) 
	{
		this.osType = osType;
	}
	
	public String getOsVer() 
	{
		return osVer;
	}
	
	public void setOsVer(String osVer) 
	{
		this.osVer = osVer;
	}
}
